image: rocker/tidyverse

pipelines:
  default:
    - step:
        script:
          - apt-get default_jre
          - apt-get default-jdk
          - cd /opt/atlassian/pipelines/agent/build
          - Rscript -e 'install.packages("devtools")'
          - Rscript -e 'devtools::install_deps(".", dependencies=TRUE, upgrade=FALSE)'
          - Rscript -e 'devtools::build()'
          - Rscript -e 'devtools::install(upgrade_dependencies = FALSE)'
          - Rscript -e 'devtools::check()'